In [1]:
import numpy as np

array = np.random.randint(1,100, size =(5,5))
print(array)

[[ 7 82 49 88 65]
 [94 32 90 37 39]
 [91 66 23 34 71]
 [61 31 27  8  3]
 [50 82 17 59 41]]


In [3]:
# Middle element of each row of array
middle = array[:, array.shape[1] // 2]
print("Middle element of each row is", middle)

Middle element of each row is [49 90 23 27 17]


In [4]:
# Mean of each row of the Array
x = np.mean(array, axis=1)
print("Mean of each row is", x)

Mean of each row is [58.2 58.4 57.  26.  49.8]


In [5]:
x = np.mean(array, axis=1)
# Generating new array containing only values greater than the mean of each row
new_array = array[array > x[:, None]]
print("Elements greater than row mean:", new_array)

Elements greater than row mean: [82 88 65 94 90 91 66 71 61 31 27 50 82 59]


In [6]:
matrix = np.array(array)
def spiral_order(matrix):
    result = []
    rows, cols = matrix.shape

    top, bottom = 0, rows - 1
    left, right = 0, cols - 1

    while top <= bottom and left <= right:

        for i in range(left, right + 1):
            result.append(matrix[top, i])
        top += 1

        for i in range(top, bottom + 1):
            result.append(matrix[i, right])
        right -= 1

        if top <= bottom:
            for i in range(right, left - 1, -1):
                result.append(matrix[bottom, i])
            bottom -= 1

        if left <= right:
            for i in range(bottom, top - 1, -1):
                result.append(matrix[i, left])
            left += 1

    return result  

print(matrix)
res = spiral_order(matrix)
print("Spiral order is:", res)

[[ 7 82 49 88 65]
 [94 32 90 37 39]
 [91 66 23 34 71]
 [61 31 27  8  3]
 [50 82 17 59 41]]
Spiral order is: [np.int32(7), np.int32(82), np.int32(49), np.int32(88), np.int32(65), np.int32(39), np.int32(71), np.int32(3), np.int32(41), np.int32(59), np.int32(17), np.int32(82), np.int32(50), np.int32(61), np.int32(91), np.int32(94), np.int32(32), np.int32(90), np.int32(37), np.int32(34), np.int32(8), np.int32(27), np.int32(31), np.int32(66), np.int32(23)]
